apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: w16
spec:
  template:
    spec:
      containers:
      - image: ko://go.seankhliao.com/mono/svc/cmd/w16
        args:
        - -compact
