# Webhook PDB.
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: webhook-pdb
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: "1.0.0"
    serving.knative.dev/release: "v1.0.0"
spec:
  selector:
    matchLabels:
      app: webhook
  minAvailable: 80%
