apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: knative-serving
  labels:
    app: controller
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: "1.0.0"
    serving.knative.dev/release: "v1.0.0"
spec:
  selector:
    app: controller
  ports:
  # Define metrics and profiling for them to be accessible within service meshes.
  - name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
