apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: git
resources:
  - deployment.cgit.k8s.yaml
  - httpproxy.cgit.k8s.yaml
  - namespace.git.k8s.yaml
  - service.cgit.k8s.yaml
  - statefulset.git.k8s.yaml
