apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otelcol
resources:
  - namespace.otelcol.k8s.yaml
  - service.otelcol.k8s.yaml
  - statefulset.otelcol.k8s.yaml
configMapGenerator:
  - name: otelcol
    files:
      - config.yaml
