apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otelcol
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
  serviceName: otelcol
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
    spec:
      containers:
        - name: otelcol
          image: index.docker.io/otel/opentelemetry-collector-contrib
          args:
            - --config=/config/config.yaml
          ports:
            - containerPort: 4317
              name: otlpgrpc
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: otelcol
