apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: w16
build:
  artifacts:
    - image: index.docker.io/seankhliao/paste
      ko:
        main: ./svc/cmd/paste
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
  local:
    concurrency: 0
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
      - ./deploy/c32/paste
