apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: mono
build:
  artifacts:
  - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/replaceme
    kaniko:
      dockerfile: ci/Dockerfile
      image: gcr.io/kaniko-project/executor:latest
      registryMirror: mirror.gcr.io
      reproducible: true
      singleSnapshot: true
      skipUnusedStages: true
      target: replaceme
      useNewRun: true
      whitelistVarRun: true
      buildArgs:
        GOPROXY: http://athens.athens.svc.cluster.local
        GOCACHE: /var/run/gobuildcache
        GOMODCACHE: /var/run/gomodcache
      volumeMounts:
        - name: modcache
          mountPath: /var/run/gomodcache
        - name: buildcache
          mountPath: /var/run/gobuildcache
  cluster:
    pullSecretName: kaniko-secret
    pullSecretPath: kaniko-secret
    namespace: skaffold
    volumes:
      - name: modcache
        hostPath:
          path: /opt/kind/cluster30/kaniko-gomodcache
      - name: buildcache
        hostPath:
          path: /opt/kind/cluster30/kaniko-gobuildcache
deploy:
  kubeContext: kind-cluster30
  kustomize:
    paths:
      - kube/overlays/cluster30/replaceme
profiles:
  - name: archrepod
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/archrepod
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: archrepod
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/archrepod
  - name: feedagg
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/feedagg
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: feedagg
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/feedagg
  - name: ghdefaults
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/ghdefaults
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: ghdefaults
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/ghdefaults
  - name: medea
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/singlepage
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: singlepage
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/medea
  - name: paste
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/paste
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: paste
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/paste
  - name: vanity
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/vanity
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: vanity
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/vanity
  - name: w16
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: europe-north1-docker.pkg.dev/com-seankhliao/kluster/w16
      - op: replace
        path: /build/artifacts/0/kaniko/target
        value: w16
      - op: replace
        path: /deploy/kustomize/paths/0
        value: kube/overlays/cluster30/w16
