apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: mono-ko
build:
  artifacts:
    - image: ko://replace-me
      ko:
        flags:
          - -trimpath
        ldflags:
          - -s
          - -w
      hooks:
        after:
          - command:
              - sh
              - -c
              - COSIGN_PASSWORD= cosign sign --key secret/cosign/cosign.key $SKAFFOLD_IMAGE
  local:
    concurrency: 0
  tagPolicy:
    sha256: {}
deploy:
  kustomize:
    paths:
      - ./deploy/replace-me
profiles:
  - name: authd
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/authd
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/authd
  - name: authn
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/authn
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/authn
  - name: earbug
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/earbug
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/earbug
  - name: ghdefaults
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/ghdefaults
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/ghdefaults
  - name: paste
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/paste
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/paste
  - name: reqsink
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/reqsink
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/reqsink
  - name: w16
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ko://go.seankhliao.com/mono/svc/cmd/w16
      - op: replace
        path: /deploy/kustomize/paths/0
        value: ./deploy/c32/w16
