apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: mono
build:
  artifacts:
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/archrepod
      bazel:
        target: //go/cmd/archrepod:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/feedagg
      bazel:
        target: //go/cmd/feedagg:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/ghdefaults
      bazel:
        target: //go/cmd/ghdefaults:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/singlepage
      bazel:
        target: //go/cmd/singlepage:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/paste
      bazel:
        target: //go/cmd/paste:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/vanity
      bazel:
        target: //go/cmd/vanity:image.tar
    - image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/w16
      bazel:
        target: //go/cmd/w16:image.tar
deploy:
  kubeContext: default
  kustomize:
    paths:
      - kube/overlays/cluster31
