# Source: cert-manager/templates/webhook-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: "cert-manager"
  labels:
    app: webhook
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
    app.kubernetes.io/version: "v1.5.0"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 10250
