admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 27000

overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
    - name: envoy.resource_monitors.fixed_heap
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
        max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
    - name: envoy.overload_actions.shrink_heap
      triggers:
        - name: envoy.resource_monitors.fixed_heap
          threshold:
            value: 0.95
    - name: envoy.overload_actions.stop_accepting_requests
      triggers:
        - name: envoy.resource_monitors.fixed_heap
          threshold:
            value: 0.98

static_resources:
  listeners:
    - name: http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                normalize_path: true
                merge_slashes: true
                path_with_escaped_slashes_action: REJECT_REQUEST
                common_http_protocol_options: &commonhttp
                  idle_timeout: 3600s # 1 hour
                  headers_with_underscores_action: REJECT_REQUEST
                http_filters:
                  - name: envoy.filters.http.router
                route_config:
                  virtual_hosts:
                    - name: all
                      domains:
                        - "*"
                      routes:
                        match:
                          prefix: /
                        redirect:
                          https_redirect: true

    - name: https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      listener_filters:
        - name: "envoy.filters.listener.tls_inspector"
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      filter_chains:
        - filter_chain_match:
            server_names:
              - envoy.seankhliao.com
              - ghdefaults.seankhliao.com
              - grafana.seankhliao.com
              - medea.seankhliao.com
              - paste.seankhliao.com
              - prometheus.seankhliao.com
              - stylesheet.seankhliao.com
              - w16.seankhliao.com
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context: &commontls
                tls_certificates:
                  - certificate_chain:
                      filename: /etc/letsencrypt/_.seankhliao.com.crt
                    private_key:
                      filename: /etc/letsencrypt/_.seankhliao.com.key
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                normalize_path: true
                merge_slashes: true
                path_with_escaped_slashes_action: REJECT_REQUEST
                common_http_protocol_options: *commonhttp
                http2_protocol_options:
                  max_concurrent_streams: 100
                  initial_stream_window_size: 65536 # 64 KiB
                  initial_connection_window_size: 1048576 # 1 MiB
                # access_log:
                #   - name: envoy.access_loggers.stdout
                #     typed_config:
                #       "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                route_config:
                  virtual_hosts: &h2hosts
                    - name: envoy
                      domains:
                        - envoy.seankhliao.com
                      response_headers_to_add: &quichdr
                        - header:
                            key: alt-svc
                            value: h3=":10000"; ma=86400, h3-29=":10000"; ma=86400
                      routes:
                        match:
                          prefix: /
                        direct_response:
                          status: 200
                          body:
                            inline_string: Hello Envoy
                    - name: ghdefaults
                      domains:
                        - ghdefaults.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: ghdefaults
                    - name: grafana
                      domains:
                        - grafana.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: grafana
                    - name: medea
                      domains:
                        - medea.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: medea
                    - name: paste
                      domains:
                        - paste.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: paste
                    - name: prometheus
                      domains:
                        - prometheus.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: prometheus
                    - name: stylesheet
                      domains:
                        - stylesheet.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: stylesheet
                    - name: w16
                      domains:
                        - w16.seankhliao.com
                      response_headers_to_add: *quichdr
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: w16
        - filter_chain_match:
            server_names:
              - auth-test.seankhliao.com
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context: *commontls
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                normalize_path: true
                merge_slashes: true
                path_with_escaped_slashes_action: REJECT_REQUEST
                common_http_protocol_options: *commonhttp
                http2_protocol_options:
                  max_concurrent_streams: 100
                  initial_stream_window_size: 65536 # 64 KiB
                  initial_connection_window_size: 1048576 # 1 MiB
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: authd
                      transport_api_version: V3
                  - name: envoy.filters.http.router
                route_config:
                  virtual_hosts:
                    - name: auth-test
                      domains:
                        - auth-test.seankhliao.com
                      routes:
                        match:
                          prefix: /
                        route:
                          cluster: medea
                        # direct_response:
                        #   status: 200
                        #   body:
                        #     inline_string: Hello Auth test
    - name: http3
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
          protocol: UDP
      reuse_port: true
      udp_listener_config:
        quic_options: {}
        downstream_socket_config:
          prefer_gro: true
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.quic
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
              downstream_tls_context:
                common_tls_context: *commontls
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: HTTP3
                stat_prefix: ingress_http
                use_remote_address: true
                normalize_path: true
                merge_slashes: true
                path_with_escaped_slashes_action: REJECT_REQUEST
                common_http_protocol_options: *commonhttp
                http3_protocol_options: {}
                # access_log:
                #   - name: envoy.access_loggers.stdout
                #     typed_config:
                #       "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

                http_filters:
                  - name: envoy.filters.http.router
                route_config:
                  virtual_hosts: *h2hosts

  clusters:
    - name: authd
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: authd
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28006
    - name: ghdefaults
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: ghdefaults
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28003
                health_check_config:
                  port_value: 27003
      health_checks: &basichealth
        - timeout:
            seconds: 1
          interval:
            seconds: 10
          unhealthy_threshold: 3
          healthy_threshold: 1
          http_health_check:
            path: /healthz
    - name: grafana
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: grafana
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 3000
                health_check_config:
                  port_value: 3000
      health_checks:
        - timeout:
            seconds: 1
          interval:
            seconds: 10
          unhealthy_threshold: 3
          healthy_threshold: 1
          http_health_check:
            path: /api/health
    - name: medea
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: medea
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28002
                health_check_config:
                  port_value: 27002
      health_checks: *basichealth
    - name: paste
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: paste
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28004
                health_check_config:
                  port_value: 27004
      health_checks: *basichealth
    - name: prometheus
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: prometheus
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9090
                health_check_config:
                  port_value: 9090
      health_checks:
        - timeout:
            seconds: 1
          interval:
            seconds: 10
          unhealthy_threshold: 3
          healthy_threshold: 1
          http_health_check:
            path: /-/ready
    - name: stylesheet
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: stylesheet
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28005
                health_check_config:
                  port_value: 27005
      health_checks: *basichealth
    - name: w16
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      load_assignment:
        cluster_name: w16
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 28001
                health_check_config:
                  port_value: 27001
      health_checks: *basichealth
