apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: paste
spec:
  template:
    spec:
      containers:
        - image: ko://go.seankhliao.com/mono/svc/cmd/paste
          args:
            - -otlp.endpoint=otelcol.otelcol.svc:4317
