apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoycert
  namespace: projectcontour
spec:
  revisionHistoryLimit: 1
  commonName: envoy
  duration: 87600h
  issuerRef:
    name: contour-ca
  privateKey:
    algorithm: ECDSA
  secretName: envoycert
