substitutions:
  _IMG: vanity
  _REG: us-central1-docker.pkg.dev/com-seankhliao/run

steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - -c=.
      - -f=ci/Dockerfile
      - -d=$_REG/$_IMG:latest
      - --cache=true
      - --reproducible
      - --single-snapshot
      - --skip-unused-stages
      - --target=vanity
      - --use-new-run

  - id: deploy
    name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: gcloud
    args:
      - run
      - deploy
      - go-seankhliao-com
      - --image=$_REG/$_IMG:latest
      - --region=us-central1
      - --platform=managed
