substitutions:
  _IMG: go.seankhliao.com/mono/svc/cmd/vanity
  _REG: us-central1-docker.pkg.dev/com-seankhliao/run

steps:
  - id: build-push-deploy
    name: us-central1-docker.pkg.dev/com-seankhliao/run/ko
    entrypoint: sh
    args:
      - -c
      - >
        set -ex
        && img=$(ko publish --preserve-import-paths $_IMG)
        && gcloud run deploy seankhliao-com
            --image=${img}
            --region=us-central1
            --platform=managed
    env:
      - KO_DOCKER_REPO=$_REG
