substitutions:
  _IMG: go.seankhliao.com/mono/svc/cmd/w16
  _REG: us-central1-docker.pkg.dev/com-seankhliao/run

steps:
  - id: generate
    name: us-central1-docker.pkg.dev/com-seankhliao/run/ko
    entrypoint: go
    args:
      - run
      - go.seankhliao.com/mono/cli/cmd/webrender
      - -src=content/seankhliao.com
      - -dst=static/seankhliao.com
      - -gtm=GTM-TLVN7D6
    volumes: &govols
      - name: gomodcache
        path: /gomodcache
      - name: gobuildcache
        path: /gocache
  - id: build-push
    name: us-central1-docker.pkg.dev/com-seankhliao/run/ko
    entrypoint: ko
    args:
      - publish
      - --preserve-import-paths
      - $_IMG
    env:
      - KO_DOCKER_REPO=$_REG
    volumes: *govols

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - seankhliao-com
      - --image=$_REG/$_IMG:latest
      - --region=us-central1
      - --platform=managed
