substitutions:
  _IMG: w16
  _REG: us-central1-docker.pkg.dev/com-seankhliao/run

steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:v1.6.0
    args:
      - -c=.
      - -f=ci/Dockerfile
      - -d=$_REG/$_IMG:latest
      - --cache=true
      - --reproducible
      - --single-snapshot
      - --skip-unused-stages
      - --target=w16
      - --use-new-run

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - seankhliao-com
      - --image=$_REG/$_IMG:latest
      - --region=us-central1
      - --platform=managed
