substitutions:
  _IMG: go.seankhliao.com/mono/svc/cmd/w16
  _REG: us-central1-docker.pkg.dev/com-seankhliao/run

steps:
  - id: build-push
    name: us-central1-docker.pkg.dev/com-seankhliao/run/ko:v0.9.3
    args:
      - publish
      - --preserve-import-path
      - $_IMG
    env:
      KO_DOCKER_REPO: $_REG

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: gcloud
    args:
      - run
      - deploy
      - seankhliao-com
      - --image=$_REG/$_IMG:latest
      - --region=us-central1
      - --platform=managed
