apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-contour-internal
  labels:
    networking.knative.dev/ingress-provider: contour
roleRef:
  name: knative-contour
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: contour
  namespace: contour-internal
  kind: ServiceAccount
