apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: contour-internal
  labels:
    networking.knative.dev/ingress-provider: contour
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
