apiVersion: apps/v1
kind: Deployment
metadata:
  name: authd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authd
    spec:
      containers:
        - name: authd
          image: index.docker.io/seankhliao/authd
          ports:
            - name: h2c
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /authd
      volumes:
        - name: config
          secret:
            secretName: authd
