apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipelines-leader-election
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
rules:
# We uses leases for leaderelection
- resources: ["leases"]
  apiGroups: ["coordination.k8s.io"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
