apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanity
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - args: []
          name: vanity
          image: docker.seankhliao.com/vanity:latest
          env: []
          ports:
            - name: http
              containerPort: 8080
      enableServiceLinks: false
      serviceAccountName: vanity
      terminationGracePeriodSeconds: 10
