apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs
resources:
  - ../../../secret/kustomize/seaweedfs
  - namespace.seaweedfs.k8s.yaml
  - service.seaweedfs.k8s.yaml
  - statefulset.seaweedfs.k8s.yaml
