apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: loki
resources:
  - service.loki.k8s.yaml
  - statefulset.loki.k8s.yaml
configMapGenerator:
  - name: loki
    files:
      - config.yaml
