apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
resources:
  - httpproxy.jaeger.k8s.yaml
  - namespace.jaeger.k8s.yaml
  - service.jaeger.k8s.yaml
  - statefulset.jaeger.k8s.yaml
