apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
    - name: grpc
      port: 14250
      targetPort: grpc
    - name: http
      port: 16686
      targetPort: http
  selector:
    app.kubernetes.io/name: jaeger
