apiVersion: apps/v1
kind: Deployment
metadata:
  name: earbug
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: earbug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: earbug
    spec:
      containers:
        - name: earbug
          image: index.docker.io/seankhliao/earbug
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: earbug
