apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.cilium-operator.k8s.yaml
- clusterrole.cilium.k8s.yaml
- clusterrolebinding.cilium-operator.k8s.yaml
- clusterrolebinding.cilium.k8s.yaml
- configmap.cilium-config.k8s.yaml
- daemonset.cilium.k8s.yaml
- deployment.cilium-operator.k8s.yaml
- secret.hubble-ca-secret.k8s.yaml
- secret.hubble-server-certs.k8s.yaml
- serviceaccount.cilium-operator.k8s.yaml
- serviceaccount.cilium.k8s.yaml
