env:
  CGO_ENABLED: "0"
  GOFLAGS: "-trimpath"
steps:
  - group: go latest
    steps:
      - label: go vet
        depends_on: ~
        command: ~/go/bin/go vet ./...
      - label: go test
        depends_on: ~
        command: ~/go/bin/go test ./...
      - label: go build
        depends_on: ~
        commands:
          - ~/go/bin/go version
          - ~/go/bin/go build -ldflags='-s -w' -o /dev/null ./...
  - group: go tip
    steps:
      - label: go vet
        depends_on: ~
        command: ~/go/bin/gotip vet ./...
      - label: go test
        depends_on: ~
        command: ~/go/bin/gotip test ./...
      - label: go build
        depends_on: ~
        commands:
          - mkdir -p bin
          - ~/go/bin/gotip version
          - ~/go/bin/gotip build -ldflags='-s -w' -o bin/ ./...
          - rm -rf ~/staging-bin
          - mkdir -p ~/staging-bin
          - cp bin/* ~/staging-bin
  - wait
  - group: deploy to medea
    steps:
    - label: replace existing binaries
      command: sudo mv ~/staging-bin/* /usr/local/bin
    - wait
    - label: restart deployment
      command: sudo systemctl restart {{matrix}}
      matrix:
        - blog@a
        - blog@b
        - earbug
        - ghdefaults@a
        - ghdefaults@b
        - singlepage@liaodev-a
        - singlepage@liaodev-b
        - singlepage@medea-a
        - singlepage@medea-b
        - singlepage@stylesheet-a
        - singlepage@stylesheet-b
        - vanity@a
        - vanity@b
