env:
  GOMODCACHE: /var/lib/buildkite-agent/gomodcache
  GOCACHE: /var/lib/buildkite-agent/gobuildcache
  GOIMAGE: golang:alpine

steps:
  - command: |
      docker run --rm -it \
        -v ${GOMODCACHE}:/go/pkg/mod \
        -v ${GOCACHE}:/root/.cache/go-build \
        -v ${BUILDKITE_BUILD_CHECKOUT_PATH}:/workspace \
        -w /workspace \
        $GOIMAGE \
        go build ./...
