apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: debug
      image: europe-north1-docker.pkg.dev/com-seankhliao/kluster/alpine-debug:latest
      command:
        - sh
        - -c
        - sleep infinity
