# Source: cilium/templates/cilium-operator-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-operator
roleRef:
  name: cilium-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: "cilium-operator"
  namespace: kube-system
  kind: ServiceAccount
