apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: athens
resources:
  - ../../../secret/kustomize/athens
  - httpproxy.athens.k8s.yaml
  - namespace.athens.k8s.yaml
  - service.athens.k8s.yaml
  - statefulset.athens.k8s.yaml
configMapGenerator:
  - name: athens-git
    files:
      - .gitconfig=gitconfig
