# Source: cert-manager/templates/cainjector-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-cainjector
  labels:
    app: cainjector
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: "v1.5.0"
rules:
- resources: ["certificates"]
  apiGroups: ["cert-manager.io"]
  verbs: ["get", "list", "watch"]
- resources: ["secrets"]
  apiGroups: [""]
  verbs: ["get", "list", "watch"]
- resources: ["events"]
  apiGroups: [""]
  verbs: ["get", "create", "update", "patch"]
- resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  apiGroups: ["admissionregistration.k8s.io"]
  verbs: ["get", "list", "watch", "update"]
- resources: ["apiservices"]
  apiGroups: ["apiregistration.k8s.io"]
  verbs: ["get", "list", "watch", "update"]
- resources: ["customresourcedefinitions"]
  apiGroups: ["apiextensions.k8s.io"]
  verbs: ["get", "list", "watch", "update"]
- resources: ["auditsinks"]
  apiGroups: ["auditregistration.k8s.io"]
  verbs: ["get", "list", "watch", "update"]
