# Source: cert-manager/templates/cainjector-rbac.yaml
# leader election rules
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-cainjector:leaderelection
  namespace: kube-system
  labels:
    app: cainjector
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: "v1.5.0"
rules:
# Used for leader election by the controller
# cert-manager-cainjector-leader-election is used by the CertificateBased injector controller
#   see cmd/cainjector/start.go#L113
# cert-manager-cainjector-leader-election-core is used by the SecretBased injector controller
#   see cmd/cainjector/start.go#L137
# See also: https://github.com/kubernetes-sigs/controller-runtime/pull/1144#discussion_r480173688
- resources: ["configmaps"]
  apiGroups: [""]
  resourceNames: ["cert-manager-cainjector-leader-election", "cert-manager-cainjector-leader-election-core"]
  verbs: ["get", "update", "patch"]
- resources: ["configmaps"]
  apiGroups: [""]
  verbs: ["create"]
- resources: ["leases"]
  apiGroups: ["coordination.k8s.io"]
  resourceNames: ["cert-manager-cainjector-leader-election", "cert-manager-cainjector-leader-election-core"]
  verbs: ["get", "update", "patch"]
- resources: ["leases"]
  apiGroups: ["coordination.k8s.io"]
  verbs: ["create"]
