# Source: cert-manager/templates/cainjector-rbac.yaml
# grant cert-manager permission to manage the leaderelection configmap in the
# leader election namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-cainjector:leaderelection
  namespace: kube-system
  labels:
    app: cainjector
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: "v1.5.0"
roleRef:
  name: cert-manager-cainjector:leaderelection
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: cert-manager-cainjector
  namespace: cert-manager
  kind: ServiceAccount
