apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipelines-webhook-cluster-access
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
roleRef:
  name: tekton-pipelines-webhook-cluster-access
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: tekton-pipelines-webhook
  namespace: tekton-pipelines
  kind: ServiceAccount
