apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
spec:
  template:
    spec:
      serviceAccountName: local-path-provisioner
      containers:
      - name: local-path-provisioner
        image: rancher/local-path-provisioner:v0.0.21
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        imagePullPolicy: IfNotPresent
      volumes:
      - name: config-volume
        configMap:
          name: local-path-config
