apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: peerauthentications.security.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    istio: security
    release: istio
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: security.istio.io
  names:
    kind: PeerAuthentication
    categories:
    - istio-io
    - security-istio-io
    listKind: PeerAuthenticationList
    plural: peerauthentications
    shortNames:
    - pa
    singular: peerauthentication
  scope: Namespaced
  versions:
  - name: v1beta1
    additionalPrinterColumns:
    - name: Mode
      type: string
      description: Defines the mTLS mode used for peer authentication.
      jsonPath: .spec.mtls.mode
    - name: Age
      type: date
      description: 'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: PeerAuthentication defines how traffic will be tunneled (or not) to the sidecar.
            properties:
              selector:
                type: object
                description: The selector determines the workloads to apply the ChannelAuthentication on.
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
              mtls:
                type: object
                description: Mutual TLS settings for workload.
                properties:
                  mode:
                    type: string
                    description: Defines the mTLS mode used for peer authentication.
                    enum:
                    - UNSET
                    - DISABLE
                    - PERMISSIVE
                    - STRICT
              portLevelMtls:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    mode:
                      type: string
                      description: Defines the mTLS mode used for peer authentication.
                      enum:
                      - UNSET
                      - DISABLE
                      - PERMISSIVE
                      - STRICT
                description: Port specific mutual TLS settings.
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
