apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: networking.istio.io
  names:
    kind: Gateway
    categories:
    - istio-io
    - networking-istio-io
    listKind: GatewayList
    plural: gateways
    shortNames:
    - gw
    singular: gateway
  scope: Namespaced
  versions:
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: 'Configuration affecting edge load balancer. See more details at: https://istio.io/docs/reference/config/networking/gateway.html'
            properties:
              selector:
                type: object
                additionalProperties:
                  type: string
              servers:
                type: array
                description: A list of server specifications.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: An optional name of the server, when set must be unique across all servers.
                    port:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Label assigned to the port.
                        protocol:
                          type: string
                          description: The protocol exposed on the port.
                        targetPort:
                          type: integer
                        number:
                          type: integer
                          description: A valid non-negative integer port number.
                    bind:
                      type: string
                    defaultEndpoint:
                      type: string
                    hosts:
                      type: array
                      description: One or more hosts exposed by this gateway.
                      items:
                        type: string
                    tls:
                      type: object
                      description: Set of TLS related options that govern the server's behavior.
                      properties:
                        caCertificates:
                          type: string
                          description: REQUIRED if mode is `MUTUAL`.
                        cipherSuites:
                          type: array
                          description: 'Optional: If specified, only support the specified cipher list.'
                          items:
                            type: string
                        credentialName:
                          type: string
                        httpsRedirect:
                          type: boolean
                        maxProtocolVersion:
                          type: string
                          description: 'Optional: Maximum TLS protocol version.'
                          enum:
                          - TLS_AUTO
                          - TLSV1_0
                          - TLSV1_1
                          - TLSV1_2
                          - TLSV1_3
                        minProtocolVersion:
                          type: string
                          description: 'Optional: Minimum TLS protocol version.'
                          enum:
                          - TLS_AUTO
                          - TLSV1_0
                          - TLSV1_1
                          - TLSV1_2
                          - TLSV1_3
                        mode:
                          type: string
                          enum:
                          - PASSTHROUGH
                          - SIMPLE
                          - MUTUAL
                          - AUTO_PASSTHROUGH
                          - ISTIO_MUTUAL
                        privateKey:
                          type: string
                          description: REQUIRED if mode is `SIMPLE` or `MUTUAL`.
                        serverCertificate:
                          type: string
                          description: REQUIRED if mode is `SIMPLE` or `MUTUAL`.
                        subjectAltNames:
                          type: array
                          items:
                            type: string
                        verifyCertificateHash:
                          type: array
                          items:
                            type: string
                        verifyCertificateSpki:
                          type: array
                          items:
                            type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: 'Configuration affecting edge load balancer. See more details at: https://istio.io/docs/reference/config/networking/gateway.html'
            properties:
              selector:
                type: object
                additionalProperties:
                  type: string
              servers:
                type: array
                description: A list of server specifications.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: An optional name of the server, when set must be unique across all servers.
                    port:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Label assigned to the port.
                        protocol:
                          type: string
                          description: The protocol exposed on the port.
                        targetPort:
                          type: integer
                        number:
                          type: integer
                          description: A valid non-negative integer port number.
                    bind:
                      type: string
                    defaultEndpoint:
                      type: string
                    hosts:
                      type: array
                      description: One or more hosts exposed by this gateway.
                      items:
                        type: string
                    tls:
                      type: object
                      description: Set of TLS related options that govern the server's behavior.
                      properties:
                        caCertificates:
                          type: string
                          description: REQUIRED if mode is `MUTUAL`.
                        cipherSuites:
                          type: array
                          description: 'Optional: If specified, only support the specified cipher list.'
                          items:
                            type: string
                        credentialName:
                          type: string
                        httpsRedirect:
                          type: boolean
                        maxProtocolVersion:
                          type: string
                          description: 'Optional: Maximum TLS protocol version.'
                          enum:
                          - TLS_AUTO
                          - TLSV1_0
                          - TLSV1_1
                          - TLSV1_2
                          - TLSV1_3
                        minProtocolVersion:
                          type: string
                          description: 'Optional: Minimum TLS protocol version.'
                          enum:
                          - TLS_AUTO
                          - TLSV1_0
                          - TLSV1_1
                          - TLSV1_2
                          - TLSV1_3
                        mode:
                          type: string
                          enum:
                          - PASSTHROUGH
                          - SIMPLE
                          - MUTUAL
                          - AUTO_PASSTHROUGH
                          - ISTIO_MUTUAL
                        privateKey:
                          type: string
                          description: REQUIRED if mode is `SIMPLE` or `MUTUAL`.
                        serverCertificate:
                          type: string
                          description: REQUIRED if mode is `SIMPLE` or `MUTUAL`.
                        subjectAltNames:
                          type: array
                          items:
                            type: string
                        verifyCertificateHash:
                          type: array
                          items:
                            type: string
                        verifyCertificateSpki:
                          type: array
                          items:
                            type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
