apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceentries.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: networking.istio.io
  names:
    kind: ServiceEntry
    categories:
    - istio-io
    - networking-istio-io
    listKind: ServiceEntryList
    plural: serviceentries
    shortNames:
    - se
    singular: serviceentry
  scope: Namespaced
  versions:
  - name: v1alpha3
    additionalPrinterColumns:
    - name: Hosts
      type: string
      description: The hosts associated with the ServiceEntry
      jsonPath: .spec.hosts
    - name: Location
      type: string
      description: Whether the service is external to the mesh or part of the mesh (MESH_EXTERNAL or MESH_INTERNAL)
      jsonPath: .spec.location
    - name: Resolution
      type: string
      description: Service discovery mode for the hosts (NONE, STATIC, or DNS)
      jsonPath: .spec.resolution
    - name: Age
      type: date
      description: 'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: 'Configuration affecting service registry. See more details at: https://istio.io/docs/reference/config/networking/service-entry.html'
            properties:
              ports:
                type: array
                description: The ports associated with the external service.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Label assigned to the port.
                    protocol:
                      type: string
                      description: The protocol exposed on the port.
                    targetPort:
                      type: integer
                    number:
                      type: integer
                      description: A valid non-negative integer port number.
              addresses:
                type: array
                description: The virtual IP addresses associated with the service.
                items:
                  type: string
              endpoints:
                type: array
                description: One or more endpoints associated with the service.
                items:
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                      description: One or more labels associated with the endpoint.
                    serviceAccount:
                      type: string
                    ports:
                      type: object
                      additionalProperties:
                        type: integer
                      description: Set of ports associated with the endpoint.
                    address:
                      type: string
                    locality:
                      type: string
                      description: The locality associated with the endpoint.
                    network:
                      type: string
                    weight:
                      type: integer
                      description: The load balancing weight associated with the endpoint.
              exportTo:
                type: array
                description: A list of namespaces to which this service is exported.
                items:
                  type: string
              hosts:
                type: array
                description: The hosts associated with the ServiceEntry.
                items:
                  type: string
              location:
                type: string
                enum:
                - MESH_EXTERNAL
                - MESH_INTERNAL
              resolution:
                type: string
                description: Service discovery mode for the hosts.
                enum:
                - NONE
                - STATIC
                - DNS
                - DNS_ROUND_ROBIN
              subjectAltNames:
                type: array
                items:
                  type: string
              workloadSelector:
                type: object
                description: Applicable only for MESH_INTERNAL services.
                properties:
                  labels:
                    type: object
                    additionalProperties:
                      type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1beta1
    additionalPrinterColumns:
    - name: Hosts
      type: string
      description: The hosts associated with the ServiceEntry
      jsonPath: .spec.hosts
    - name: Location
      type: string
      description: Whether the service is external to the mesh or part of the mesh (MESH_EXTERNAL or MESH_INTERNAL)
      jsonPath: .spec.location
    - name: Resolution
      type: string
      description: Service discovery mode for the hosts (NONE, STATIC, or DNS)
      jsonPath: .spec.resolution
    - name: Age
      type: date
      description: 'CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
      jsonPath: .metadata.creationTimestamp
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: 'Configuration affecting service registry. See more details at: https://istio.io/docs/reference/config/networking/service-entry.html'
            properties:
              ports:
                type: array
                description: The ports associated with the external service.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Label assigned to the port.
                    protocol:
                      type: string
                      description: The protocol exposed on the port.
                    targetPort:
                      type: integer
                    number:
                      type: integer
                      description: A valid non-negative integer port number.
              addresses:
                type: array
                description: The virtual IP addresses associated with the service.
                items:
                  type: string
              endpoints:
                type: array
                description: One or more endpoints associated with the service.
                items:
                  type: object
                  properties:
                    labels:
                      type: object
                      additionalProperties:
                        type: string
                      description: One or more labels associated with the endpoint.
                    serviceAccount:
                      type: string
                    ports:
                      type: object
                      additionalProperties:
                        type: integer
                      description: Set of ports associated with the endpoint.
                    address:
                      type: string
                    locality:
                      type: string
                      description: The locality associated with the endpoint.
                    network:
                      type: string
                    weight:
                      type: integer
                      description: The load balancing weight associated with the endpoint.
              exportTo:
                type: array
                description: A list of namespaces to which this service is exported.
                items:
                  type: string
              hosts:
                type: array
                description: The hosts associated with the ServiceEntry.
                items:
                  type: string
              location:
                type: string
                enum:
                - MESH_EXTERNAL
                - MESH_INTERNAL
              resolution:
                type: string
                description: Service discovery mode for the hosts.
                enum:
                - NONE
                - STATIC
                - DNS
                - DNS_ROUND_ROBIN
              subjectAltNames:
                type: array
                items:
                  type: string
              workloadSelector:
                type: object
                description: Applicable only for MESH_INTERNAL services.
                properties:
                  labels:
                    type: object
                    additionalProperties:
                      type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
