apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-ingressgateway-sds
roleRef:
  name: istio-ingressgateway-sds
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: istio-ingressgateway-service-account
    kind: ServiceAccount
