apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
spec:
  ports:
    - name: status-port
      protocol: TCP
      port: 15021
      targetPort: 15021
    - name: http2
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http1
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
