# Source: cilium/templates/cilium-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    name: cilium-operator
    io.cilium/app: operator
spec:
  # See docs on ServerCapabilities.LeasesResourceLock in file pkg/k8s/version/version.go
  # for more details.
  replicas: 1
  selector:
    matchLabels:
      name: cilium-operator
      io.cilium/app: operator
  template:
    metadata:
      labels:
        name: cilium-operator
        io.cilium/app: operator
      annotations:
    spec:
      restartPolicy: Always
      serviceAccountName: "cilium-operator"
      serviceAccount: "cilium-operator"
      hostNetwork: true
      priorityClassName: system-cluster-critical
      containers:
        - name: cilium-operator
          image: "quay.io/cilium/operator-generic:v1.10.6@sha256:6bd47edc4d8f8b5b984509c68f5625a4141c0f5a4c8931f012b0453d9b62bd92"
          command:
            - cilium-operator-generic
          args:
            - --config-dir=/tmp/cilium/config-map
            - --debug=$(CILIUM_DEBUG)
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CILIUM_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: cilium-config
                  key: debug
                  optional: true
            - name: KUBERNETES_SERVICE_HOST
              value: "65.21.73.144"
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
          volumeMounts:
            - name: cilium-config-path
              readOnly: true
              mountPath: /tmp/cilium/config-map
          livenessProbe:
            httpGet:
              port: 9234
              host: "127.0.0.1"
              path: /healthz
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
          imagePullPolicy: IfNotPresent
      volumes:
        # To read the configuration from the config map
        - name: cilium-config-path
          configMap:
            name: cilium-config
      # In HA mode, cilium-operator pods must not be scheduled on the same
      # node as they will clash with each other.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: io.cilium/app
                    operator: In
                    values:
                      - operator
              topologyKey: kubernetes.io/hostname
      tolerations:
        - operator: Exists
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
