apiVersion: networking.x-k8s.io/v1alpha1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - port: 80
      protocol: HTTP
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            app: {{ .Values.experimental.kubernetesGateway.appLabelSelector }}
    - port: 443
      protocol: HTTPS
      tls:
        certificateRef:
          name: {{ $cert.name }}
          group: {{ $cert.group }}
          kind: {{ $cert.kind }}
      routes:
        kind: HTTPRoute
        selector:
          matchLabels:
            app: {{ $.Values.experimental.kubernetesGateway.appLabelSelector }}
