apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  # Configuration file for the mesh networks to be used by the Split Horizon EDS.
  meshNetworks: "networks: {}"
