apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.k8s.yaml
- ingressroute.k8s.yaml
- service.k8s.yaml
- serviceaccount.k8s.yaml
commonLabels:
  app.kubernetes.io/name: w16
