apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-contour
  labels:
    networking.knative.dev/ingress-provider: contour
  creationTimestamp: null
rules:
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - create
  - get
  - update
- resources:
  - endpoints
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - namespaces
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - services
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
- resources:
  - customresourcedefinitions
  apiGroups:
  - apiextensions.k8s.io
  verbs:
  - list
- resources:
  - ingressclasses
  apiGroups:
  - networking.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - ingresses
  apiGroups:
  - networking.k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - ingresses/status
  apiGroups:
  - networking.k8s.io
  verbs:
  - create
  - get
  - update
- resources:
  - backendpolicies
  - gatewayclasses
  - gateways
  - httproutes
  - tcproutes
  - tlsroutes
  - udproutes
  apiGroups:
  - networking.x-k8s.io
  verbs:
  - get
  - list
  - watch
- resources:
  - backendpolicies/status
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  - tcproutes/status
  - tlsroutes/status
  - udproutes/status
  apiGroups:
  - networking.x-k8s.io
  verbs:
  - update
- resources:
  - extensionservices
  apiGroups:
  - projectcontour.io
  verbs:
  - get
  - list
  - watch
- resources:
  - extensionservices/status
  apiGroups:
  - projectcontour.io
  verbs:
  - create
  - get
  - update
- resources:
  - httpproxies
  - tlscertificatedelegations
  apiGroups:
  - projectcontour.io
  verbs:
  - get
  - list
  - watch
- resources:
  - httpproxies/status
  apiGroups:
  - projectcontour.io
  verbs:
  - create
  - get
  - update
