apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.18.2
  namespace: contour-external
  labels:
    networking.knative.dev/ingress-provider: contour
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: contour-certgen
    spec:
      restartPolicy: Never
      serviceAccountName: contour-certgen
      containers:
      - name: contour
        image: gcr.io/knative-releases/github.com/projectcontour/contour/cmd/contour@sha256:7212e8d3fb415189d5bd361dde75816447a4bd3c5b949c74f6fe2695b9a8d2c4
        command:
        - contour
        - certgen
        - --kube
        - --incluster
        - --overwrite
        - --secrets-format=compact
        - --namespace=$(CONTOUR_NAMESPACE)
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
  ttlSecondsAfterFinished: 0
