apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contour-certgen
  namespace: contour-external
  labels:
    networking.knative.dev/ingress-provider: contour
rules:
- resources:
  - secrets
  apiGroups:
  - ""
  verbs:
  - create
  - update
