apiVersion: v1
kind: Service
metadata:
  name: contour
  namespace: contour-external
  labels:
    networking.knative.dev/ingress-provider: contour
spec:
  type: ClusterIP
  selector:
    app: contour
  ports:
  - name: xds
    protocol: TCP
    port: 8001
    targetPort: 8001
