apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gerrit
resources:
  - httpproxy.gerrit.k8s.yaml
  - namespace.gerrit.k8s.yaml
  - service.gerrit.k8s.yaml
  - statefulset.gerrit.k8s.yaml
