# Source: cni/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cni-repair-role
rules:
  - resources: ["pods"]
    apiGroups: [""]
    verbs: ["get", "list", "watch", "delete", "patch", "update"]
  - resources: ["events"]
    apiGroups: [""]
    verbs: ["get", "list", "watch", "delete", "patch", "update", "create"]
