# Source: cni/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cni
rules:
  - resources:
      - pods
      - nodes
    apiGroups: [""]
    verbs:
      - get
