apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-cni-config
data:
  # The CNI network configuration to add to the plugin chain on each node.  The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "cniVersion": "0.3.1",
      "name": "istio-cni",
      "type": "istio-cni",
      "log_level": "info",
      "log_uds_address": "__LOG_UDS_ADDRESS__",
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__",
          "cni_bin_dir": "/opt/cni/bin",
          "exclude_namespaces": [ "istio-system", "kube-system" ]
      }
    }
