apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: istio-cni
resources:
  - clusterrole.istio-cni-repair-role.k8s.yaml
  - clusterrole.istio-cni.k8s.yaml
  - clusterrolebinding.istio-cni-repair-rolebinding.k8s.yaml
  - clusterrolebinding.istio-cni.k8s.yaml
  - configmap.istio-cni-config.k8s.yaml
  - daemonset.istio-cni-node.k8s.yaml
  - serviceaccount.istio-cni.k8s.yaml
