apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: 9096
      targetPort: grpc
  selector:
    app.kubernetes.io/name: loki
