apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paste
resources:
  - ../../../svc/cmd/paste/kustomize
  - ../../base/etcd
  - namespace.paste.k8s.yaml
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: StatefulSet
          name: etcd
        fieldPaths:
          - spec.template.spec.volumes.0.hostPath.path
        options:
          delimiter: /
          index: 3
