apiVersion: apps/v1
kind: Deployment
metadata:
  name: earbug
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: earbug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: earbug
    spec:
      containers:
        - name: earbug
          image: ko://go.seankhliao.com/mono/svc/cmd/earbug
          args:
            - -otlp.endpoint=otelcol.otelcol.svc:4317
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - secretRef:
                name: earbug
