apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: seaweedfs
resources:
  - ../../../secret/kustomize/seaweedfs
  - service.seaweedfs.k8s.yaml
  - statefulset.seaweedfs.k8s.yaml
