apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maddy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  serviceName: maddy
  template:
    spec:
      enableServiceLinks: false
      serviceAccountName: maddy
      containers:
        - name: maddy
          image: docker.io/foxcpp/maddy:latest
          ports:
          - name: smtp
            containerPort: 25
            hostPort: 25
          - name: submittls
            containerPort: 465
            hostPort: 465
          - name: imaptls
            containerPort: 993
            hostPort: 993
          - name: metrics
            containerPort: 9749
          volumeMounts:
            - name: config
              mountPath: /data/maddy.conf
              subPath: maddy.conf
            - name: data
              mountPath: /data
            - name: tls
              mountPath: /var/run/secrets/tls
      volumes:
        - name: config
          configMap:
            name: maddy
        - name: tls
          secret:
            secretName: maddy-tls
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
