apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vanity
bases:
  - ../../../base/vanity
resources:
  - namespace.k8s.yaml
images:
  - name: docker.seankhliao.com/vanity
    newName: europe-north1-docker.pkg.dev/com-seankhliao/kluster/vanity
