# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-pipelines-controller-cluster-access
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
rules:
- # Controller needs to watch Pods created by TaskRuns to see them progress.
  resources: ["pods"]
  apiGroups: [""]
  verbs: ["list", "watch"]
  # Controller needs cluster access to all of the CRDs that it is responsible for
  # managing.
- resources: ["tasks", "clustertasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources", "conditions", "runs"]
  apiGroups: ["tekton.dev"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- resources: ["taskruns/finalizers", "pipelineruns/finalizers", "runs/finalizers"]
  apiGroups: ["tekton.dev"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- resources: ["tasks/status", "clustertasks/status", "taskruns/status", "pipelines/status", "pipelineruns/status", "pipelineresources/status", "runs/status"]
  apiGroups: ["tekton.dev"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
