apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.tekton-pipelines-controller-cluster-access.k8s.yaml
- clusterrole.tekton-pipelines-controller-tenant-access.k8s.yaml
- clusterrolebinding.tekton-pipelines-controller-cluster-access.k8s.yaml
- clusterrolebinding.tekton-pipelines-controller-tenant-access.k8s.yaml
- deployment.tekton-pipelines-controller.k8s.yaml
- role.tekton-pipelines-controller.k8s.yaml
- rolebinding.tekton-pipelines-controller-leaderelection.k8s.yaml
- rolebinding.tekton-pipelines-controller.k8s.yaml
- service.tekton-pipelines-controller.k8s.yaml
- serviceaccount.tekton-pipelines-controller.k8s.yaml
