apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-controller-leaderelection
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
roleRef:
  name: tekton-pipelines-leader-election
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: tekton-pipelines-controller
  namespace: tekton-pipelines
  kind: ServiceAccount
