# Source: cert-manager/templates/rbac.yaml
# Certificates controller role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-certificates
  labels:
    app: cert-manager
    app.kubernetes.io/component: "controller"
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/version: "v1.5.0"
rules:
- resources: ["certificates", "certificates/status", "certificaterequests", "certificaterequests/status"]
  apiGroups: ["cert-manager.io"]
  verbs: ["update"]
- resources: ["certificates", "certificaterequests", "clusterissuers", "issuers"]
  apiGroups: ["cert-manager.io"]
  verbs: ["get", "list", "watch"]
# We require these rules to support users with the OwnerReferencesPermissionEnforcement
# admission controller enabled:
# https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement
- resources: ["certificates/finalizers", "certificaterequests/finalizers"]
  apiGroups: ["cert-manager.io"]
  verbs: ["update"]
- resources: ["orders"]
  apiGroups: ["acme.cert-manager.io"]
  verbs: ["create", "delete", "get", "list", "watch"]
- resources: ["secrets"]
  apiGroups: [""]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- resources: ["events"]
  apiGroups: [""]
  verbs: ["create", "patch"]
