apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  ports:
    - name: dns
      protocol: UDP
      port: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
    - name: metrics
      protocol: TCP
      port: 9153
  clusterIP: 172.17.0.10
